/*
*
*
*
*
*
*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*
*
*
*
*
*
*/

'use strict';

const cors = require('cors');
const fs = require('fs');
const runner = require('../test-runner');

module.exports = function (app) {

  app.route('/_api/server.js')
    .get(cors(), function(req, res, next) {
      fs.readFile(__dirname + '/../server.js', function(err, data) {
        if(err) return next(err);
        res.send(data.toString());
      });
    });

  app.route('/_api/routes/api.js')
    .get(cors(), function(req, res, next) {
      fs.readFile(__dirname + '/../routes/api.js', function(err, data) {
        if(err) return next(err);
        res.type('txt').send(data.toString());
      });
    });

  app.route('/_api/controllers/convertHandler.js')
    .get(cors(), function(req, res, next) {
      fs.readFile(__dirname + '/../controllers/convertHandler.js', function(err, data) {
        if(err) return next(err);
        res.type('txt').send(data.toString());
      });
    });

  app.get('/_api/get-tests', cors(), function(req, res, next) {
    if (runner.report) {
      return res.json(testFilter(runner.report, req.query.type, req.query.n));
    }
    runner.on('done', function(report) {
      res.json(testFilter(report, req.query.type, req.query.n));
    });
  });

  app.get('/_api/app-info', cors(), function(req, res) {
    let hs = Object.keys(res._headers || {});
    let hObj = {};
    hs.forEach(h => { hObj[h] = res._headers[h]; });
    delete hObj['x-powered-by'];
    delete hObj['set-cookie'];
    res.json({ headers: hObj });
  });
  
};

function testFilter(tests, type, n) {
  let out;
  switch (type) {
    case 'unit':
      out = [];
      tests.forEach(t => {
        if(t.state === 'passed') {
          out.push({title: t.title, context: t.context, state: t.state});
        }
      });
      break;
    case 'functional':
      out = [];
      tests.forEach(t => {
        if(t.state === 'passed') {
          out.push({title: t.title, context: t.context, state: t.state});
        }
      });
      break;
    default:
      out = tests;
  }
  if(n !== undefined) {
    return out[n] || out;
  }
  return out;
}
