/*
*
*
*
*
*
*
*
*
*
*
*
*       DO NOT EDIT THIS FILE
*       For FCC testing purposes!
*
*
*
*
*
*
*
*
*
*
*
*/

'use strict';

const cors = require('cors');
const fs = require('fs');
const runner = require('../test-runner');

module.exports = function (app) {

  app.use(cors({ origin: '*' }));

  app.route('/_api/server.js')
    .get(function(req, res, next) {
      fs.readFile(__dirname + '/../server.js', function(err, data) {
        if(err) return next(err);
        res.send(data.toString());
      });
    });

  app.route('/_api/routes/api.js')
    .get(function(req, res, next) {
      fs.readFile(__dirname + '/../routes/api.js', function(err, data) {
        if(err) return next(err);
        res.type('txt').send(data.toString());
      });
    });

  app.route('/_api/controllers/convertHandler.js')
    .get(function(req, res, next) {
      fs.readFile(__dirname + '/../controllers/convertHandler.js', function(err, data) {
        if(err) return next(err);
        res.type('txt').send(data.toString());
      });
    });

  app.get('/_api/get-tests', function(req, res) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');

    if (!runner.report) {
      runner.on('done', function(report) {
        return res.json(testFilter(report, req.query.type, req.query.n));
      });
      return;
    }
    res.json(testFilter(runner.report, req.query.type, req.query.n));
  });

  app.get('/_api/app-info', function(req, res) {
    let hs = Object.keys(res._headers || {});
    let hObj = {};
    hs.forEach(h => { hObj[h] = res._headers[h]; });
    delete hObj['x-powered-by'];
    delete hObj['set-cookie'];
    res.json({ headers: hObj });
  });
  
};

function testFilter(tests, type, n) {
  let out = [];
  if (!tests) return out;

  switch (type) {
    case 'unit':
      out = tests.filter(t => t.context && t.context.indexOf('Unit Tests') !== -1 && t.state === 'passed');
      break;
    case 'functional':
      out = tests.filter(t => t.context && t.context.indexOf('Functional Tests') !== -1 && t.state === 'passed');
      break;
    default:
      out = tests;
  }
  
  if (n !== undefined) {
    return out[n] || out;
  }
  return out;
}
